#!/usr/bin/php -dopcache.jit_buffer_size=65536
<?php

declare(strict_types=1);

if (PHP_VERSION_ID < 80000) {
    die("Requires PHP8 or higher.\n");
}
$aOpcacheStatus = opcache_get_status();
if (isset($aOpcacheStatus['jit'])) {
    echo "JIT parameters: ";
    print_r($aOpcacheStatus['jit']);
} else {
    echo "JIT mode disabled\n";
}

